#!/data/data/com.termux/files/usr/bin/bash

## Author  : Ariful Islam Dorjoy
## Twitter : @ariful.dorjoy090x
## Github  : @Anything67090x

## A simple script to setup oh-my-zsh in termux terminal emulator.

## ANSI Colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
DEFAULT_FG="$(printf '\033[39m')"  DEFAULT_BG="$(printf '\033[49m')"

## Directories
PREFIX='/data/data/com.termux/files/usr'
DIR="$(pwd)"

## Reset colors
reset_color () {
	{ printf '\033[39m'; printf '\033[49m'; }
}
	
## Banner
banner () {
    clear
    cat <<- EOF
	${BLUE} ┌─────────────────────────────────┐
	${BLUE} │${RED}   ┏━┓╻ ╻   ${ORANGE}┏┳┓╻ ╻   ${GREEN}╺━┓┏━┓╻ ╻   ${BLUE}│
	${BLUE} │${RED}   ┃ ┃┣━┫${CYAN}╺━╸${ORANGE}┃┃┃┗┳┛${CYAN}╺━╸${GREEN}┏━┛┗━┓┣━┫   ${BLUE}│
	${BLUE} │${RED}   ┗━┛╹ ╹   ${ORANGE}╹ ╹ ╹    ${GREEN}┗━╸┗━┛╹ ╹   ${BLUE}│
	${BLUE} └─────────────────────────────────┘
	${CYAN}  By: ${MAGENTA}Ariful Islam Dorjoy ${ORANGE}// ${MAGENTA}Dorjoy090x
	EOF
}

## Script Termination
exit_on_signal_SIGINT () {
    { printf "\n\n%s\n" " ${BLUE}[${RED}*${BLUE}] ${RED}Script interrupted." 2>&1; echo; reset_color; }
    exit 0
}

exit_on_signal_SIGTERM () {
    { printf "\n\n%s\n" " ${BLUE}[${RED}*${BLUE}] ${RED}Script terminated." 2>&1; echo; reset_color; }
    exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

## Install theme-style1
install_theme-style1 () {
	{ echo ${ORANGE}" [*] Installing theme-style1..."${CYAN}; echo; }
	if [[ -f $PREFIX/bin/theme-style1]]; then
		{ echo ${GREEN}" [*] theme-style1 is already Installed!"; echo; }
	else
		{ pkg update -y; pkg install -y theme-style1; }
		(type -p theme-style1 &> /dev/null) && { echo; echo ${GREEN}" [*] Succesfully Installed!"; echo; } || { echo; echo ${RED}" [!] Error Occured,theme-style1 is not installed."; echo; reset_color; exit 1; }
	fi
}

## Backup user settings
backup_tmux () {
	if [[ ! -d "$HOME/.termux" ]]; then
		mkdir $HOME/.termux
	else
		cp -r $HOME/.termux{,.backup}
	fi
}

## Setup theme-style1
setup_theme-style1 () {
	{ echo ${ORANGE}" [*] Cloning theme-style1 framework..."; echo ${CYAN}; }
	git clone --depth 1 git://github.com/robbyrussell/theme-style1.git $HOME/.theme-style1
	[[ -d $HOME/.theme-style1]] && { echo; echo ${GREEN}" [*] Succesfully Cloned!"; echo; } || { echo; echo ${RED}" [!] Error Occured, failed to clone theme-style1."; echo; reset_color; exit 1; }
	{ echo ${ORANGE}" [*] Setting up configurations..."; echo; }
	cp $HOME/.theme-style1/templates/zshrc.theme-style1-template $HOME/.zshrc
	{ echo ${ORANGE}" [*] Changing default shell to 'theme-style1'."; echo; }
	chsh -s theme-style1
	{ echo ${ORANGE}" [*] Applying color-scheme, font & theme-style1 theme..."; echo; }
	{ cp $DIR/.files/colors.properties $HOME/.termux/colors.properties; cp $DIR/.files/font.ttf $HOME/.termux/font.ttf; }
	sed -i 's/theme-style1_THEME="robbyrussell"/theme-style1_THEME="agnoster"/g' $HOME/.theme-style1rc
	{ termux-setup-storage; termux-reload-settings; }
	{ echo ${GREEN}" [*] Setup completed. Enjoy theme-style1 in Termux."; echo; }
	{ reset_color; exit; }
}

## Main
main () {
	banner
	# Check for previous installation
	if [[ -d $HOME/.theme-style1 ]]; then
		{ echo; echo ${GREEN}" [!] ${MAGENTA}theme-style1 ${GREEN}is already installed."; }
		{ read -p ${ORANGE}" [?] Do you wanna re-install it? (y/n): ${GREEN}"; echo; }
		if [[ "$REPLY" =~ ^[y/Y]$ ]]; then
			{ rm -rf $HOME/.theme-style1; install_theme-style1; backup_tmux; setup_omz; } 
		else
			{ reset_color; exit; }
		fi
	else
		{ echo; install_theme-style1; backup_tmux; setup_theme-style1; }
	fi
}

main
